// Generated by Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import CoreGraphics;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class EventCell;

SWIFT_PROTOCOL("_TtP8Settings15CellTapListener_")
@protocol CellTapListener
- (void)tapActionWithSender:(EventCell * _Nonnull)sender;
@end

@class UIViewController;
@class PlistManager;
@class UIAlertController;

SWIFT_CLASS("_TtC8Settings13AlertListener")
@interface AlertListener : NSObject <CellTapListener>
- (nonnull instancetype)initWithController:(UIViewController * _Nonnull)controller plist:(PlistManager * _Nonnull)plist alert:(UIAlertController * _Nonnull)alert OBJC_DESIGNATED_INITIALIZER;
- (void)tapActionWithSender:(EventCell * _Nonnull)sender;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class TableContent;
@class UIColor;

SWIFT_CLASS("_TtC8Settings11CellContent")
@interface CellContent : NSObject
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title push:(TableContent * _Nonnull)push detailIndex:(NSInteger)detailIndex OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title detail:(NSString * _Nonnull)detail addTrigger:(BOOL)addTrigger OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title isOn:(BOOL)isOn OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title buttonColor:(UIColor * _Nonnull)buttonColor OBJC_DESIGNATED_INITIALIZER;
- (void)setWithTitle:(NSString * _Nonnull)title;
- (void)setWithDetail:(NSString * _Nonnull)detail;
- (void)setWithIsOn:(BOOL)isOn;
- (NSString * _Nonnull)getTitle;
- (NSString * _Nonnull)getDetail;
- (BOOL)getIsOn;
- (UIColor * _Nullable)getButtonColor;
- (BOOL)getSwitchHidden;
- (BOOL)getCoverHidden;
- (TableContent * _Nullable)getPushTableContent;
- (NSArray<id <CellTapListener>> * _Nonnull)getTapListeners;
- (NSString * _Nonnull)getKey;
- (id _Nonnull)getValue;
- (void)setWithValue:(id _Nonnull)value;
- (void)addWithTapListener:(id <CellTapListener> _Nonnull)tapListener;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP8Settings11CellFactory_")
@protocol CellFactory
- (EventCell * _Nonnull)makeCell:(CellContent * _Nonnull)content;
@end


@class UISwitch;
@class UIButton;
@class NSCoder;
@class SettingTableView;

SWIFT_CLASS("_TtC8Settings9EventCell")
@interface EventCell : UITableViewCell
@property (nonatomic, copy) UISwitch * _Nonnull (^ _Nonnull modifySwitch)(UISwitch * _Nonnull);
@property (nonatomic, copy) UIButton * _Nonnull (^ _Nonnull modifyColorButton)(UIButton * _Nonnull);
@property (nonatomic, copy) UIButton * _Nonnull (^ _Nonnull modifyCoverButton)(UIButton * _Nonnull);
- (nonnull instancetype)initWithCellContent:(CellContent * _Nonnull)cellContent OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)modifySubViews;
- (void)tapAction;
- (void)updateView;
- (SettingTableView * _Nonnull)makeTableView;
- (void)setWithTapListeners:(NSArray<id <CellTapListener>> * _Nonnull)tapListeners;
- (NSString * _Nonnull)getTitle;
- (CellContent * _Nonnull)getCellContent;
- (BOOL)getIsOn;
- (void)setContentWithDetail:(NSString * _Nonnull)detail;
- (void)layoutSubviews;
- (void)updateConstraints;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8Settings12PlistManager")
@interface PlistManager : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull plistPathInDocument;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setupWithCellContents:(NSArray<CellContent *> * _Nonnull)cellContents;
- (void)adjustCellContents;
@end


SWIFT_CLASS("_TtC8Settings12PushListener")
@interface PushListener : NSObject <CellTapListener>
- (nonnull instancetype)initWithController:(UIViewController * _Nonnull)controller plist:(PlistManager * _Nonnull)plist OBJC_DESIGNATED_INITIALIZER;
- (void)tapActionWithSender:(EventCell * _Nonnull)sender;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class UITableView;
@class NSBundle;

SWIFT_CLASS("_TtC8Settings20ReturnViewController")
@interface ReturnViewController : UIViewController
- (nonnull instancetype)initWithSender:(EventCell * _Nonnull)sender table:(UITableView * _Nonnull)table backTitle:(NSString * _Nullable)backTitle back:(void (^ _Nonnull)(void))back OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8Settings7Section")
@interface Section : NSObject
- (nonnull instancetype)initWithHeader:(NSString * _Nonnull)header footer:(NSString * _Nonnull)footer contents:(NSArray<CellContent *> * _Nonnull)contents heightForHeader:(CGFloat)heightForHeader heightForFooter:(CGFloat)heightForFooter OBJC_DESIGNATED_INITIALIZER;
- (void)addWithContent:(CellContent * _Nonnull)content;
- (NSArray<CellContent *> * _Nonnull)getcellContents;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8Settings16SettingTableView")
@interface SettingTableView : UITableView
- (nonnull instancetype)initWithContent:(TableContent * _Nonnull)content OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame style:(UITableViewStyle)style SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8Settings13ShareListener")
@interface ShareListener : NSObject <CellTapListener>
- (nonnull instancetype)initWithController:(UIViewController * _Nonnull)controller OBJC_DESIGNATED_INITIALIZER;
- (void)tapActionWithSender:(EventCell * _Nonnull)sender;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8Settings19ShareViewController")
@interface ShareViewController : UIViewController
- (nonnull instancetype)initWithSender:(EventCell * _Nonnull)sender table:(UITableView * _Nonnull)table backTitle:(NSString * _Nullable)backTitle OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8Settings17SimpleCellFactory")
@interface SimpleCellFactory : NSObject <CellFactory>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (EventCell * _Nonnull)makeCell:(CellContent * _Nonnull)content;
@end

@protocol UITableViewDelegate;

SWIFT_CLASS("_TtC8Settings12TableContent")
@interface TableContent : NSObject
- (nonnull instancetype)initWithHeader:(NSString * _Nonnull)header options:(NSArray<NSString *> * _Nonnull)options factory:(id <CellFactory> _Nonnull)factory delegate:(id <UITableViewDelegate> _Nullable)delegate allowsSelection:(BOOL)allowsSelection OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSections:(NSArray<Section *> * _Nonnull)sections factory:(id <CellFactory> _Nonnull)factory delegate:(id <UITableViewDelegate> _Nullable)delegate allowsSelection:(BOOL)allowsSelection OBJC_DESIGNATED_INITIALIZER;
- (CellContent * _Nullable)cellContentWithIndex:(NSInteger)index;
- (NSArray<Section *> * _Nonnull)getSections;
- (id <CellFactory> _Nonnull)getFactory;
- (NSArray<CellContent *> * _Nonnull)getCellContents;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8Settings17TickTableDelegate")
@interface TickTableDelegate : NSObject <UIScrollViewDelegate, UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didDeselectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
